####################
##    ariMa's     ##
##    Notebook    ##
####################

# Basic
name: "ari[Ma]'s Notebook"
url: "arima-s-notebook"
language: zh-Hans

# URL
baseurl: "/arima-s-notebook"
permalink: /:year-:month-:day/:title/

# Maekdown
markdown: kramdown
kramdown:
  input: GFM

# 跳转
navs:
  home: /

# Scopes
defaults:
  - scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  - scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# Sass
sass:
  sass_dir: /assets/css
  style: :compressed

# Highlighter
highlighter: rouge
highlight:
  line_number: true


#############
#  Scripts  #
#############
vendors:
  # JQuery
  jquery: /assets/js/jquery-3.6.0.min.js?v=3.6.0
  # 显示侧边导航栏
  shownav: /assets/js/shownav.js
  # 顶部进度条
  pbar: /assets/js/processbar.js
  # b2t按钮
  b2t: /assets/js/b2t.js
